#!/bin/bash
# publish-tfgen-package publishes the packages for a "terraform based" resource provider
# (i.e. one produced by using tfgen and tfbridge). It has some assumptions about the common
# layout we use for our terraform based resource providers.
#
# usage publish-tfgen-package <path-to-repository-root>
#
# If using this to publish a hand-written package which happens to correspond to most of the
# common tfgen layout, but does not have a python package, set NO_TFGEN_PYTHON_PACKAGE in the
# environment to any non-empty value.

set -o errexit
set -o pipefail

if [ "$#" -ne 1 ]; then
    >&2 echo "usage: $0 <path-to-repository-root>"
    exit 1
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
SOURCE_ROOT="$1"

# Before we publish, we run some validation checks over the package
if ! "${SCRIPT_ROOT}"/check-package-dependencies "${SOURCE_ROOT}/sdk/nodejs/bin/package.json"; then
    >&2 echo "checking package dependencies failed, refusing to publish"
    exit 1
fi

if [[ "${TRAVIS_OS_NAME:-}" == "linux" ]]; then
    # Publish the NPM package.
    echo "Publishing NPM package to NPMjs.com:"

    # First, add an install script to our package.json
    mkdir -p "${SOURCE_ROOT}/sdk/nodejs/bin/scripts"
    cp "${SCRIPT_ROOT}/install-pulumi-plugin.js" \
       "${SOURCE_ROOT}/sdk/nodejs/bin/scripts"
    node "${SCRIPT_ROOT}/add-plugin-installer-script.js" < \
        "${SOURCE_ROOT}/sdk/nodejs/bin/package.json" > \
        "${SOURCE_ROOT}/sdk/nodejs/bin/package.json.publish"
    pushd "${SOURCE_ROOT}/sdk/nodejs/bin"
    mv package.json package.json.dev
    mv package.json.publish package.json

    NPM_TAG="dev"

    # We use the "features/" prefix on branches that we want to build and publish for doing
    # cross repo work. But in this case, we don't want to publish over "dev", since the bits
    # could be totally busted and the dev tag tracks master.
    if [[ "${TRAVIS_BRANCH:-}" == features/* ]]; then
        NPM_TAG=$(echo "${TRAVIS_BRANCH}" | sed -e 's|^features/|feature-|g')
    fi

    # If the package doesn't have a pre-release tag, use the tag of latest instead of
    # dev. NPM uses this tag as the default version to add, so we want it to mean
    # the newest released version.
	PKG_VERSION=$(jq -r .version < package.json)
	if [[ "${PKG_VERSION}" != *-dev* ]] && [[ "${PKG_VERSION}" != *-alpha* ]]; then
        NPM_TAG="latest"
    fi

    # Now, perform the publish.
    npm publish -tag "${NPM_TAG}"
    npm info 2>/dev/null

    # And finally restore the original package.json.
    mv package.json package.json.publish
    mv package.json.dev package.json
    popd

    # Next, publish the PyPI package, if we didn't opt out
    if [ -n "${NO_TFGEN_PYTHON_PACKAGE}" ] ; then
        echo "Skipping publishing pip package because of NO_TFGEN_PYTHON_PACKAGE"
    else
        echo "Publishing Pip package to pulumi.com:"
        twine upload \
            -u pulumi -p "${PYPI_PASSWORD}" \
            "${SOURCE_ROOT}/sdk/python/bin/dist/*.tar.gz"
    fi
fi
