#!/bin/bash
set -o nounset -o errexit -o pipefail

ALL_PACKAGES=(
    "@pulumi/aws"
    "@pulumi/aws-infra"
    "@pulumi/aws-serverless"
    "@pulumi/azure"
    "@pulumi/azure-serverless"
    "@pulumi/cloud"
    "@pulumi/cloud-aws"
    "@pulumi/cloud-azure"
    "@pulumi/docker"
    "@pulumi/eks"
    "@pulumi/gcp"
    "@pulumi/kubernetes"
    "@pulumi/openstack"
    "@pulumi/pulumi"
    "@pulumi/random"
    "@pulumi/terraform-template"
    "@pulumi/vsphere"
)

echo "Installing latest Pulumi CLI"
curl -sSL https://get.pulumi.com | bash -s -- --version "$(curl -sSL "http://registry.npmjs.org/-/package/@pulumi/pulumi/dist-tags" | jq -r .dev)"

OVERRIDES="";

for PACKAGE in "${ALL_PACKAGES[@]}"; do
    echo -n "Determining latest version of ${PACKAGE}..."
    DEV_VERSION="$(curl -sSL "http://registry.npmjs.org/-/package/${PACKAGE}/dist-tags" | jq -r .dev)"

    if [ "${DEV_VERSION}" = "null" ]; then
        echo "could not compute latest version of ${PACKAGE}, is it missing a dev tag in NPM?"
    else
        echo "${DEV_VERSION}"
        OVERRIDES="${OVERRIDES}:${PACKAGE}=${DEV_VERSION}"        
    fi
done

export PULUMI_TEST_NODE_OVERRIDES="${OVERRIDES:1}"
make "travis_${TRAVIS_EVENT_TYPE}"
