#!/bin/bash
set -o nounset -o errexit -o pipefail

ALL_PACKAGES=(
    "@pulumi/alicloud"
    "@pulumi/aws"
    "@pulumi/aws-infra"
    "@pulumi/aws-serverless"
    "@pulumi/awsx"
    "@pulumi/azure"
    "@pulumi/azure-serverless"
    "@pulumi/azuread"
    "@pulumi/cloud"
    "@pulumi/cloud-aws"
    "@pulumi/cloud-azure"
    "@pulumi/cloudflare"
    "@pulumi/datadog"
    "@pulumi/digitalocean"
    "@pulumi/dnsimple"
    "@pulumi/docker"
    "@pulumi/eks"
    "@pulumi/f5bigip"
    "@pulumi/gcp"
    "@pulumi/gitlab"
    "@pulumi/kubernetes"
    "@pulumi/linode"
    "@pulumi/mysql"
    "@pulumi/newrelic"
    "@pulumi/openstack"
    "@pulumi/packet"
    "@pulumi/policy"
    "@pulumi/postgresql"
    "@pulumi/pulumi"
    "@pulumi/query"
    "@pulumi/random"
    "@pulumi/terraform"
    "@pulumi/terraform-template"
    "@pulumi/tls"
    "@pulumi/vsphere"
)

USE_LATEST_CLI=true
USE_LATEST_PACKAGES=true
SPECIFIC_VERSION=

for ARG in "$@"
do
    case "${ARG}" in
        --no-latest-cli)
            USE_LATEST_CLI=false
            ;;
        --no-latest-packages)
            USE_LATEST_PACKAGES=false
            ;;
        --version=*)
            SPECIFIC_VERSION="${ARG#*=}"
            USE_LATEST_PACKAGES=false
            USE_LATEST_CLI=false
            shift
            ;;
    esac
done

if [ "${USE_LATEST_CLI}" = "true" ]; then
    echo "Installing latest Pulumi CLI"
    curl -sSL https://get.pulumi.com | bash -s -- --version "$(curl -sSL "http://registry.npmjs.org/-/package/@pulumi/pulumi/dist-tags" | jq -r .beta)"
fi

if [ "${USE_LATEST_PACKAGES}" = "true" ]; then
    NODE_OVERRIDES="";

    echo "Processing Node packages"
    for PACKAGE in "${ALL_PACKAGES[@]}"; do
        echo -n "Determining latest version of ${PACKAGE}..."
        DEV_VERSION="$(curl -sSL "http://registry.npmjs.org/-/package/${PACKAGE}/dist-tags" | jq -r .dev)"

        if [ "${DEV_VERSION}" = "null" ]; then
            echo "could not compute latest version of ${PACKAGE}, is it missing a dev tag in NPM?"
        else
            echo "${DEV_VERSION}"
            NODE_OVERRIDES="${NODE_OVERRIDES}:${PACKAGE}=${DEV_VERSION}"
        fi
    done

    export PULUMI_TEST_NODE_OVERRIDES="${NODE_OVERRIDES:1}"
fi

if [ "${SPECIFIC_VERSION}" != "" ]; then
    echo "Installing ${SPECIFIC_VERSION} of Pulumi CLI"
    curl -sSL https://get.pulumi.com | bash -s -- --version "$(curl -sSL "http://registry.npmjs.org/-/package/@pulumi/pulumi/dist-tags" | jq -r .\"${SPECIFIC_VERSION}\")"

    NODE_OVERRIDES="";

    echo "Processing Node packages"
    for PACKAGE in "${ALL_PACKAGES[@]}"; do
        echo -n "Determining ${SPECIFIC_VERSION} version of ${PACKAGE}..."
        SPEC_VERSION="$(curl -sSL "http://registry.npmjs.org/-/package/${PACKAGE}/dist-tags" | jq -r .\"${SPECIFIC_VERSION}\")"

        if [ "${SPEC_VERSION}" = "null" ]; then
            echo -n "Determining 'dev'' version of ${PACKAGE}..."
            DEV_VERSION="$(curl -sSL "http://registry.npmjs.org/-/package/${PACKAGE}/dist-tags" | jq -r .dev)"

            if [ "${DEV_VERSION}" = "null" ]; then
                echo "could not compute latest version of ${PACKAGE}, is it missing a dev tag in NPM?"
            else
                echo "${DEV_VERSION}"
                NODE_OVERRIDES="${NODE_OVERRIDES}:${PACKAGE}=${DEV_VERSION}"
            fi
        else
            echo "${SPEC_VERSION}"
            NODE_OVERRIDES="${NODE_OVERRIDES}:${PACKAGE}=${SPEC_VERSION}"
        fi
    done

    export PULUMI_TEST_NODE_OVERRIDES="${NODE_OVERRIDES:1}"
fi
